cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(hermes_voice_button C)
target_sources(app PRIVATE ../src/main.c ../src/charge_indicator.c ../src/button.c ../src/codec.c ../src/storage.c ../src/ble.c)
target_include_directories(app PRIVATE ../src)
